version: 2.1
jobs:
  build:
    working_directory: ~/SStion-FE
    docker:
      - image: cimg/node:18.16.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Build React App
          command: npm run build
      - save_cache:
          key: app-build-cache-{{ .Branch }}
          paths:
            - ./build
      # - run:
      #     name: Deploy to Netlify
      #     command: ./node_modules/.bin/netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN --prod --dir=build
workflows:
  build-dev:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
                - /.*(ss|SS)-\d+.*/          
  build-prod:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - deploy: 
          requires:
            - build
          filters:
            tags:
              only:  /^v.*/
            branches:
              ignore: /.*/
                 
                